[network]
name = "testnet"
deployment_fee_rate = 10
epoch = "3.0"

[accounts.deployer]
mnemonic = "drama conduct illegal senior any inhale impact rain stereo hood lens long foster fluid erosion creek morning laugh shaft horror digital actor false soldier"
# Fresh wallet for v2 deployment
